/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SQLlight;

import java.sql.DriverManager;
import java.sql.SQLException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws ClassNotFoundException, SQLException {
    	int [] ids = {0, 1, 2};
    	String[] names = {"Abdullah", "Mohamed", "Maha"};
    	
    	Class.forName("org.sqlite.JDBC");
    	
    	String dbURI = "jdbc:sqlite:people.db";
    	
    	var conn = DriverManager.getConnection(dbURI);
    	
    	var stmt = conn.createStatement();
    	conn.setAutoCommit(false);
    	
    	var sql = "create table if not exists user (id integer primary key, name text not null)";
    	
    	stmt.execute(sql);
    	
    	
    	/* sql = "insert into user (id, name) values (2, 'Haytham')";
    	stmt.execute(sql);
    	
    	sql = "insert into user (id, name) values (3, 'Lolo')";
    	stmt.execute(sql); */
    	
    	sql = "insert into user (id, name) values (?, ?)";
    	var insertStmt = conn.prepareStatement(sql);
    	
    	for (int i = 0; i < ids.length; i++) {
    		insertStmt.setInt(1,  ids[i]);
    		insertStmt.setString(2,  names[i]);
    		
    		insertStmt.executeUpdate();
    	}
    	insertStmt.close();

    	sql = "select id, name from user";
    	var rs = stmt.executeQuery(sql);
    	
    	while(rs.next()) {
    		int id = rs.getInt("id");
    		String name = rs.getString("name");
    		
    		System.out.println("Id -- Name : " + id + " - " + name);
    	}

    	sql = "drop table user";
    	stmt.execute(sql);

    	stmt.close();
    	
    	conn.close();
    }
}
